### ISSUE TITLE
Part 1 and CI/CD

### ISSUE THREAD

**Issue by louiewang820** [UBC-MDS/IMDB_Viz_R#39]

**Comment by rkrishnan-arjun** [comment]
Modification: Added a new visualization for showing the top 5 movies based on rating in the selected Genre.
Source: Peer review by Raul Aguilar
https://github.ubc.ca/fdandrea/532-peer-review/issues/8#issuecomment-23076
Team member: Arjun Radhakrishnan

Commit/s: 
https://github.com/UBC-MDS/IMDB_Viz_R/commit/befc7e6ba52b1002f29287a017ffe6c737613613
https://github.com/UBC-MDS/IMDB_Viz_R/commit/e8ae9a6c6ecfafc5129294e173a5e17d380c47f8
