### ISSUE TITLE
part 1 and improve ReadMe

### ISSUE THREAD

**Issue by louiewang820** [UBC-MDS/IMDB_Viz_R#41]

**Comment by mikeguron** [comment]
[Link to issue with details of Part 1 Additions](https://github.com/UBC-MDS/IMDB_Viz_R/issues/62#issue-1630020354)

**Comment by mikeguron** [comment]
[Link to issue with details of README Improvements](https://github.com/UBC-MDS/IMDB_Viz_R/issues/64#issue-1630066607)
